### ISSUE TITLE
Notice page broken

### ISSUE THREAD

**Issue by grigorescu** [grigorescu/Brownian#24]
IOError at /notices/
SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[KIGJNDI6RFyhxC_hgAoZbw][bro-201412011500][0]: SearchParseException[[bro-201412011500][0]: query[ConstantScore(QueryWrapperFilter(ConstantScore(*:*)))],from[-1],size[-1],sort[<custom:"ts": org.elasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSource@7ae156a5>]: Parse Failure [Failed to parse source [{"sort": {"ts": {"order": "DESC"}}, "query": {"constant_score": {"filter": {"query": {"query_string": {"query": "*"}}}}}, "facets": {"notices": {"terms": {"field": "note", "size": 25}}, "ips": {"terms": {"field": ["src", "dst"], "size": 25}}, "ports": {"terms": {"field": "p", "size": 25}}}, "from": 0, "size": 0}]]]; nested: ElasticsearchParseException[unknown parameter [field] while parsing terms facet [ips]]; }{[KIGJNDI6RFyhxC_hgAoZbw][bro-201412011800][0]: SearchParseException[[bro-201412011800][0]: query[ConstantScore(QueryWrapperFilter(ConstantScore(*:*)))],from[-1],size[-1],sort[<custom:"ts": org.elasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSource@7f9d390>]: Parse Failure [Failed to parse source [{"sort": {"ts": {"order": "DESC"}}, "query": {"constant_score": {"filter": {"query": {"query_string": {"query": "*"}}}}}, "facets": {"notices": {"terms": {"field": "note", "size": 25}}, "ips": {"terms": {"field": ["src", "dst"], "size": 25}}, "ports": {"terms": {"field": "p", "size": 25}}}, "from": 0, "size": 0}]]]; nested: ElasticsearchParseException[unknown parameter [field] while parsing terms facet [ips]]; }{[KIGJNDI6RFyhxC_hgAoZbw][bro-201412012100][0]: SearchParseException[[bro-201412012100][0]: query[ConstantScore(QueryWrapperFilter(ConstantScore(*:*)))],from[-1],size[-1],sort[<custom:"ts": org.elasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSource@5fffa9a9>]: Parse Failure [Failed to parse source [{"sort": {"ts": {"order": "DESC"}}, "query": {"constant_score": {"filter": {"query": {"query_string": {"query": "*"}}}}}, "facets": {"notices": {"terms": {"field": "note", "size": 25}}, "ips": {"terms": {"field": ["src", "dst"], "size": 25}}, "ports": {"terms": {"field": "p", "size": 25}}}, "from": 0, "size": 0}]]]; nested: ElasticsearchParseException[unknown parameter [field] while parsing terms facet [ips]]; }

**Comment by 616e6f6e796d6f** [comment]
Got the same issue...
