### ISSUE TITLE
elasticsearch 1.4.3 or 1.5.2 can't work

### ISSUE THREAD

**Issue by jiamo** [grigorescu/Brownian#27]
Error! Could not connect to server - please check ELASTICSEARCH_SERVER in settings.py

while http://localhost:9200/_cat/indices?v  give output

    health status index                pri rep docs.count docs.deleted store.size pri.store.size 
    yellow open   .packetbeat-topology   5   1          0            0       575b           575b 
    yellow open   bro-201505041800       5   1       4461            0      1.7mb          1.7mb 
    yellow open   @bro-meta              5   1          1            1      3.5kb          3.5kb 

and already add elasticsearch config.yml

    http.cors.enable: true
    http.cors.allow-origin: http://localhost:8000

bro version:
    
    engine@engine:~/Git/Brownian$ bro -N Bro::ElasticSearch
    Bro::ElasticSearch - ElasticSearch log writer (dynamic, version 1.0)

**Comment by bhennigar** [comment]
Did you run 'make && make install' from the bro/aux/plugins/elasticsearch
directory after installing bro?

**Comment by jiamo** [comment]
yes
I think  bro -N Bro::ElasticSearch can show I already installed

**Comment by bhennigar** [comment]
In your bro/share/bro/site/local.bro, have you added *@load
tuning/logs-to-elasticsearch to the file?*

**Comment by bhennigar** [comment]
you may need to move it to the tuning directory as well
Copy from local git directory
bro/lib/bro/plugins/Bro_ElasticSearch/scripts/Bro/ElasticSearch/logs-to-elasticsearch.bro
To
/bro/share/bro/policy/tuning/

**Comment by jiamo** [comment]
must to /bro/share/bro/policy/tuning/? 
I copy to /usr/local/bro/share/bro/elasticsearch
and in local


    @load elasticsearch/logs-to-elasticsearch
     
    export {
    redef Log::enable_local_logging = F;
    #redef LogAscii::json_timestamps = JSON::TS_ISO8601;
    }

**Comment by grigorescu** [comment]
Since you have an index named bro-201505041800, data is flowing into ElasticSearch from Bro, so I don't think your Bro configuration is the issue.

Do you get an error if you set the time range to all time?

**Comment by bhennigar** [comment]
That location should be good too. I'm just going by my install notes. I was
using elasticsearch 1.4.4 at the time and it worked.

Have you started bro and confirmed that it's logging to bro/logs/current?
It will still log there even with the elasticsearch plugin enabled. If I
recall, Brownian will report that it can't connect to elasticsearch until
logs have been generated. Sometimes not for 5-10 minutes depending on the
amount of traffic.

**Comment by jiamo** [comment]
I try in another machine, This error gone (have another error , never mind something new, `SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures` ) 

What difference between two machine, one is vm and the work one is physic . The only difference with bro is one using  pf_ring cluster from this link https://www.bro.org/sphinx-git/configuration/index.html which I think should make no difference with my physic one(All is defaut configure). I will try tomorrow with the vm one.

**Comment by jiamo** [comment]
@bhennigar  yes bro to ElasticSearch in vm looks like right. but vm's Brownian is the same as phyical one.  So `Could not connect to server `  seem strange.  What can cause this error while ElasticSearch was running? (Even I don't start bro ) , So the problem is between Brownian and ElasticSearch.
