### ISSUE TITLE
settings.py syntax

### ISSUE THREAD

**Issue by yehias** [grigorescu/Brownian#29]
hey just curios about database settings what db should be linked? shall I create new database or what? or link bro db if so shall it be created first ? thanks

**Comment by grigorescu** [comment]
The default database is sqlite, and is just used for session management. Configuring the database is described in the README (For development, "In settings.py, modify the DATABASES setting to the path you'd like a small SQLite database created (your user will need write permissions to both the file and the parent directory).", and for production, "In settings.py, modify the DATABASES setting to the path you'd like a small SQLite database created (your Apache user will need write permissions to both the file and the parent directory)."). The commands for creating the database are also described there (the syncdb command, though the exact syntax varies based on dev/prod).

For your actual Bro data, that will need to be in Elasticsearch, and you just point settings.py to your Elasticsearch server.

**Comment by yehias** [comment]
I just need to know to configure and create DB since in readme nothing talked about it thanks

**Comment by yehias** [comment]
just help me about it

**Comment by grigorescu** [comment]
Hi,

Can you be a bit more specific about what problems you're having? My understanding of the issues you're running into is that it's not clear how you need to configure the DATABASES setting in settings.py? Is that correct? If that's the case, please reread the README, as the parts that I quoted should help you get up and running.

There are actually two "databases" in use here - the database specified in settings.py is just used for the web app, for maintaining session data. Additionally, all your Bro logs are going into ElasticSearch.

Are you receiving a specific error?

**Comment by yehias** [comment]
please because I didn't get about db where I have to find it so I can link it I just don't know what actual database should be configured in settings.py and where I should find both databases so I can linked it I'm noob with it that's why thanks in advance

**Comment by grigorescu** [comment]
Do you have your Bro logs going into ElasticSearch already?

**Comment by yehias** [comment]
not yet shall I configure elasticsearch with bro first?

**Comment by yehias** [comment]
I already have elasticsearch installed and configure it with suricata selks interface and  I want to link bro with it I just know that I can create another .yaml file for bro so shall I done wwith it first?

**Comment by grigorescu** [comment]
Yes, please follow the process documented here:

https://www.bro.org/sphinx/components/bro-plugins/elasticsearch/README.html

**Comment by yehias** [comment]
ok thanks a lot I will finish it then get back to you

**Comment by yehias** [comment]
everything done now I can connect to 127.0.0.1:8000 I just getting 

Error! Could not connect to server - please check ELASTICSEARCH_SERVER in settings.py

**Comment by grigorescu** [comment]
Ok... What do you get if you run: 

curl 'localhost:9200/_cat/indices?v' | grep bro

**Comment by yehias** [comment]
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1209  100  1209    0     0  18979      0 --:--:-- --:--:-- --:--:-- 19190

**Comment by grigorescu** [comment]
That means that you don't have any Bro logs in ElasticSearch.

**Comment by yehias** [comment]
but I already have elasticsearch up and running and already working with selks right now and already added @load Bro/ElasticSearch/logs-to-elasticsearch.bro to local.bro

**Comment by grigorescu** [comment]
I'm going to close this issue. These issues are for bugs or feature requests in the code, not for end-user help.

Please e-mail bro@bro.org with any questions on how to get Bro logs into ElasticSearch.

**Comment by yehias** [comment]
ok thanks a lot really
