### ISSUE TITLE
Brownian does not work in Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by ghaeini** [grigorescu/Brownian#33]
Hi.
I configured the Brownian based on your instructions and the following link:
http://www.hyperionavenue.com/?p=692

My configurations are:
Elasticsearch 2.3.3
Bro 2.4.1
Ubuntu 16.04 LTS

I followed the procedure and it works on Ubuntu 14.04.
I wondering why it is not working in the new version of Ubuntu.
I did this for testing the elasticsearch.

curl 'localhost:9200/_cat/indices?v' | grep bro
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   270  100   270    0     0   4302      0 --:--:-- --:--:-- --:--:--  4354
yellow open   @bro-meta          5   1          1           11      4.8kb          4.8kb 
yellow open   bro-201605312100   5   1          0            0       795b           795b 

But it looks that elasticsearch is working fine.
But the brownian show this error:
Error! Could not connect to server - please check ELASTICSEARCH_SERVER in settings.py 

Could please help me to solve this problem?

Thanks.

**Comment by valix2fr** [comment]
Hello, Do you have solved your problems ? i have the same problems.

**Comment by grigorescu** [comment]
Hello,

No, Brownian doesn't work with ElasticSearch 2.x. This might be addressed in the future, but hasn't been yet.
